modLoader = "kotlinforforge"
loaderVersion = "[1.6,)" # Require at least 1.6.x
license = 'GNU GPLv3'
issueTrackerURL = "https://github.com/Kamefrede/slimesnsteam/issues"

[[mods]]
modId = "slimesnsteam"
version = "${version}"
displayName = "Slimes 'n' Steam"
credits = "Kamefrede, Adrian & BumbleDani"
authors = "Kamefrede"
description = '''
Steampunk automation and slime husbandry mod
'''

[[dependencies.slimesnsteam]]
modId = "forge"
mandatory = true
versionRange = "[34.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slimesnsteam]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3, 1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slimesnsteam]]
modId = "patchouli"
mandatory = true
versionRange = "[1.16-45,)"
side = "BOTH"

[[dependencies.slimesnsteam]]
modId = "curios"
mandatory = true
versionRange = "[1.16.3-4.0.1.0,)"
ordering = "AFTER"
side = "BOTH"
